API_key = "ed34fb09af38fb4e532ee24f4198fe89"
lat = ""
lon = ""
URL_weather_check = f"https://api.openweathermap.org/data/2.5/weather?lat={lat}&lon={lon}&appid={API_key}"
city_name = ""
state_code = ""
country_code = ""
limit = 1
URL_city_to_location = f"http://api.openweathermap.org/geo/1.0/"
